SELECT * FROM customer_data;
--Q1. What is the total revenue generated by male vs. female customers?
SELECT 
 gender,
 Sum(purchase_amount)
FROM
 customer_data
GROUP BY
 gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
  customer_id as customer, 
   discount_applied,
   purchase_amount
FROM
  customer_data
WHERE 
  (discount_applied = 'Yes') 
  AND purchase_amount > 
  (SELECT
  avg(purchase_amount)
  FROM customer_data
  ) 
  
--Q3. Which are the top 5 products with the highest average review rating?
SELECT 
  item_purchased,
  Round(avg(review_rating::numeric),2)
FROM
customer_data
GROUP BY
 item_purchased
order BY
  avg(review_rating) Desc
  limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
 SELECT
 shipping_type,
 Avg(purchase_amount)
FROM
customer_data
WHERE
 shipping_type = 'Express' or shipping_type = 'Standard'
GROUP BY
 shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
 subscription_status,
 count(customer_id) as no_of_customers,
 avg(purchase_amount) as average_spent,
 Sum(purchase_amount) as total_revenue
FROM
 customer_data
GROUP BY
subscription_status
ORDER BY
 average_spent, total_revenue desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
  
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
  With customer_type as(
   SELECT
    customer_id,previous_purchases,
   case 
    when previous_purchases between 1 and 10 then 'new_customer'
    when previous_purchases between 10 and 20 then 'returning_customer'
    else 'loyal'
    end as customer_segment
from 
   customer_data
  )
Select 
  customer_segment,
 count(customer_segment) as "number_of_customer"
From 
 customer_type
GROUP BY 
  customer_segment;
  
--Q8. What are the top 3 most purchased products within each category?
With item_count as(
Select
 category,
 item_purchased,
 count(customer_id) as no_of_purchases,
 ROW_NUMBER() over(partition by category ORDER BY count(customer_id)) As item_rank 
 FROM customer_data
 GROUP BY
  category,item_purchased)
Select category, item_purchased, item_rank, no_of_purchases
from item_count
WHERE
 item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 SELECT
 subscription_status,
 count(previous_purchases)
 From
  customer_data
WHERE 
 previous_purchases > 5
GROUP BY 
 subscription_status;

--Q10. What is the revenue contribution of each age group?
 SELECT
 age_group,
 Sum(purchase_amount) as total_revenue
from
 customer_data
GROUP BY
 age_group
ORDER BY
 total_revenue desc;
 
